FROM eclipse-temurin:17-jre

WORKDIR /app

# Install Kafka
RUN wget https://archive.apache.org/dist/kafka/3.7.0/kafka_2.13-3.7.0.tgz && \
    tar xzf kafka_2.13-3.7.0.tgz && \
    mv kafka_2.13-3.7.0 /opt/kafka && \
    rm kafka_2.13-3.7.0.tgz

ENV PATH=$PATH:/opt/kafka/bin

CMD ["bash", "-c", "zookeeper-server-start.sh /opt/kafka/config/zookeeper.properties & sleep 10 && kafka-server-start.sh /opt/kafka/config/server.properties"]